# Generated by Django 4.2.7 on 2026-02-19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_shipment_shipmentevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentWorkflowStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('stage_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('requires_customer_action', models.BooleanField(default=False)),
                ('customer_action_completed', models.BooleanField(default=False)),
                ('customer_action_note', models.TextField(blank=True)),
                ('customer_action_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.TextField(blank=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stages', to='trading.shipment')),
            ],
            options={
                'db_table': 'shipment_workflow_stages',
                'ordering': ['stage_order'],
                'unique_together': {('shipment', 'stage_order'), ('shipment', 'code')},
            },
        ),
    ]
