# Generated by Django 4.2.9 on 2026-02-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_email_verified_user_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='identity_documents/'),
        ),
    ]
