# Generated by Django 4.2.9 on 2026-02-06 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaults', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_change_24h', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'metals',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('convert', 'Convert'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('storage_fee', 'Storage Fee')], max_length=20)),
                ('amount_oz', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_per_oz', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='trading.metal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('purity', models.CharField(max_length=20)),
                ('weight_oz', models.DecimalField(decimal_places=4, max_digits=10)),
                ('premium_per_oz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(choices=[('bar', 'Bar'), ('coin', 'Coin'), ('digital', 'Digital')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='trading.metal')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_oz', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('serial_numbers', models.JSONField(blank=True, default=list)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('vaulted', 'Vaulted'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='vaulted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_items', to='trading.metal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_items', to='trading.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
                ('vault_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='vaults.vault')),
            ],
            options={
                'db_table': 'portfolio_items',
            },
        ),
        migrations.AddIndex(
            model_name='metal',
            index=models.Index(fields=['symbol'], name='metals_symbol_a46e10_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='transaction_user_id_08c743_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['metal', 'is_active'], name='products_metal_i_123cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['user', 'status'], name='portfolio_i_user_id_64f452_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['vault_location'], name='portfolio_i_vault_l_e2a30d_idx'),
        ),
    ]
