# Generated by Django 4.2.9 on 2026-02-08 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0002_shipment_shipmentevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_notes', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to='trading.transaction')),
            ],
            options={
                'db_table': 'transaction_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction'], name='transaction_transac_cd5971_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.UUIDField()),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_actions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['admin_user'], name='admin_actio_admin_u_289a77_idx'), models.Index(fields=['timestamp'], name='admin_actio_timesta_2d4e8c_idx'), models.Index(fields=['action_type'], name='admin_actio_action__d7b108_idx')],
            },
        ),
    ]
