# Generated by Django 4.2.9 on 2026-02-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_devemail'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devemail',
            new_name='dev_emails_created_9ccf19_idx',
            old_name='dev_emails_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='devemail',
            new_name='dev_emails_status_e681d7_idx',
            old_name='dev_emails_status_idx',
        ),
    ]
