# Generated by Django 4.2.9 on 2026-02-06 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('carrier', models.CharField(choices=[('fedex', 'FedEx'), ('brinks', 'Brinks'), ('malca', 'Malca-Amit')], max_length=20)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('customs', 'In Customs'), ('delivered', 'Delivered')], default='processing', max_length=20)),
                ('destination_address', models.JSONField()),
                ('estimated_arrival', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.deliveryrequest')),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='trading.portfolioitem')),
            ],
            options={
                'db_table': 'delivery_items',
            },
        ),
        migrations.CreateModel(
            name='DeliveryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='delivery.deliveryrequest')),
            ],
            options={
                'verbose_name_plural': 'Delivery histories',
                'db_table': 'delivery_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryrequest',
            index=models.Index(fields=['user', 'status'], name='delivery_re_user_id_7709da_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrequest',
            index=models.Index(fields=['tracking_number'], name='delivery_re_trackin_a19c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryitem',
            index=models.Index(fields=['delivery_request'], name='delivery_it_deliver_439438_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryitem',
            index=models.Index(fields=['portfolio_item'], name='delivery_it_portfol_80a2c6_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryhistory',
            index=models.Index(fields=['delivery_request', 'timestamp'], name='delivery_hi_deliver_b65807_idx'),
        ),
    ]
