# Generated by Django 4.2.9 on 2026-02-06 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('storage_fee_percent', models.DecimalField(decimal_places=4, max_digits=5)),
                ('is_allocated', models.BooleanField(default=True)),
                ('is_insured', models.BooleanField(default=True)),
                ('capacity_percent', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vaults',
                'indexes': [models.Index(fields=['status'], name='vaults_status_e19169_idx')],
            },
        ),
    ]
